apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: {{ .Values.namespace }}
data:
  POSTGRES_USER: {{ .Values.config.POSTGRES_USER | quote }}
  POSTGRES_PASSWORD: {{ .Values.config.POSTGRES_PASSWORD | quote }}
  POSTGRES_DB: {{ .Values.config.POSTGRES_DB | quote }}