apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: {{ .Values.namespace }}
data:
  MYSQL_DATABASE: {{ .Values.config.MYSQL_DATABASE | quote }}
  MYSQL_USER: {{ .Values.config.MYSQL_USER | quote }}