apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.pv.name }}
  namespace: {{ .Values.namespace }}
  labels:
    type: local
spec:
  capacity:
    storage: {{ .Values.pv.capacity }}
  accessModes:
    {{- toYaml .Values.pv.accessModes | nindent 4 }}
  hostPath:
    path: {{ .Values.pv.hostPath }}