apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.secret.MYSQL_ROOT_PASSWORD | b64enc | default "" }}
  MYSQL_PASSWORD: {{ .Values.secret.MYSQL_PASSWORD | b64enc | default "" }}